### ISSUE TITLE
TS2571 Object is of type 'unknown'

### ISSUE THREAD

**Issue by AshkanLaei** [webview/webview_deno#104]
I was trying to run this example code:
```js
// main.js
import { Webview } from "https://deno.land/x/webview/mod.ts";

const html = `
  <html>
  <body>
    <h1>Hello from deno v${Deno.version.deno}</h1>
  </body>
  </html>
`;

const webview = new Webview();
webview.navigate(`data:text/html,${encodeURIComponent(html)}`);
webview.run();
```
This is the output:
```js
Download https://deno.land/x/webview/mod.ts
Warning Implicitly using latest version (0.7.0-pre.1) for https://deno.land/x/webview/mod.ts
Download https://deno.land/x/webview@0.7.0-pre.1/mod.ts
Download https://deno.land/x/webview@0.7.0-pre.1/src/ffi.ts
Download https://deno.land/x/webview@0.7.0-pre.1/src/webview.ts
Download https://deno.land/x/webview@0.7.0-pre.1/deps.ts
Download https://deno.land/x/plug@0.5.1/plug.ts
Download https://deno.land/x/plug@0.5.1/deps.ts
Download https://deno.land/std@0.122.0/fmt/colors.ts
Download https://deno.land/std@0.122.0/path/mod.ts
Download https://deno.land/x/cache@0.2.13/mod.ts
Download https://deno.land/std@0.122.0/_util/os.ts
Download https://deno.land/std@0.122.0/path/_interface.ts
Download https://deno.land/std@0.122.0/path/common.ts
Download https://deno.land/std@0.122.0/path/glob.ts
Download https://deno.land/std@0.122.0/path/posix.ts
Download https://deno.land/std@0.122.0/path/separator.ts
Download https://deno.land/std@0.122.0/path/win32.ts
Download https://deno.land/x/cache@0.2.13/cache.ts
Download https://deno.land/std@0.122.0/_util/assert.ts
Download https://deno.land/std@0.122.0/path/_constants.ts
Download https://deno.land/std@0.122.0/path/_util.ts
Download https://deno.land/x/cache@0.2.13/deps.ts
Download https://deno.land/x/cache@0.2.13/directories.ts
Download https://deno.land/x/cache@0.2.13/file.ts
Download https://deno.land/x/cache@0.2.13/helpers.ts
Download https://deno.land/x/cache@0.2.13/file_fetcher.ts
Download https://deno.land/std@0.97.0/fs/ensure_dir.ts
Download https://deno.land/std@0.97.0/fs/exists.ts
Download https://deno.land/std@0.97.0/hash/mod.ts
Download https://deno.land/std@0.97.0/path/mod.ts
Download https://deno.land/std@0.97.0/hash/_wasm/hash.ts
Download https://deno.land/std@0.97.0/hash/hasher.ts
Download https://deno.land/std@0.97.0/fs/_util.ts
Download https://deno.land/std@0.97.0/_util/os.ts
Download https://deno.land/std@0.97.0/path/_interface.ts
Download https://deno.land/std@0.97.0/path/common.ts
Download https://deno.land/std@0.97.0/path/glob.ts
Download https://deno.land/std@0.97.0/path/posix.ts
Download https://deno.land/std@0.97.0/path/separator.ts
Download https://deno.land/std@0.97.0/path/win32.ts
Download https://deno.land/std@0.97.0/encoding/base64.ts
Download https://deno.land/std@0.97.0/encoding/hex.ts
Download https://deno.land/std@0.97.0/hash/_wasm/wasm.js
Download https://deno.land/std@0.97.0/_util/assert.ts
Download https://deno.land/std@0.97.0/path/_constants.ts
Download https://deno.land/std@0.97.0/path/_util.ts
Check file:///home/ashkan/gui/main.js
error: TS2571 [ERROR]: Object is of type 'unknown'.
    sys.symbols.deno_webview_get_recv().then((recv) => {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/webview@0.7.0-pre.1/src/webview.ts:63:5

TS7006 [ERROR]: Parameter 'recv' implicitly has an 'any' type.
    sys.symbols.deno_webview_get_recv().then((recv) => {
                                              ~~~~
    at https://deno.land/x/webview@0.7.0-pre.1/src/webview.ts:63:47

Found 2 errors.
```

**Comment by matteoturini** [comment]
Are you on Arch Linux? The Arch Linux build isn't working because its *two versions behind*. It works on latest Deno 1.19.1.

**Comment by AshkanLaei** [comment]
> Are you on Arch Linux? The Arch Linux build isn't working because its _two versions behind_. It works on latest Deno 1.19.1.

Thank you very much.
Yes, I'm using Arch Linux. `deno help` said that my deno version is 1.17.1, so I ran `deno upgrade` and now it's up to date.
It works perfectly now! so I'll close this issue.
![image](https://user-images.githubusercontent.com/50172698/155869968-6a7bac38-bc2d-4d3f-b195-46bbbbbd3f2c.png)
