### ISSUE TITLE
Example not working in macOS

### ISSUE THREAD

**Issue by martin-braun** [webview/webview_deno#106]
```sh
$ deno run -Ar --unstable https://deno.land/x/webview/examples/local.ts
...
Check https://deno.land/x/webview/examples/local.ts
error: TS2571 [ERROR]: Object is of type 'unknown'.
    sys.symbols.deno_webview_get_recv().then((recv) => {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/webview@0.7.0-pre.1/src/webview.ts:63:5

TS7006 [ERROR]: Parameter 'recv' implicitly has an 'any' type.
    sys.symbols.deno_webview_get_recv().then((recv) => {
                                              ~~~~
    at https://deno.land/x/webview@0.7.0-pre.1/src/webview.ts:63:47

Found 2 errors.

$ deno --version
deno 1.17.3 (release, x86_64-apple-darwin)
v8 9.7.106.15
typescript 4.5.2
```

Just reporting. :)

**Comment by b-fuze** [comment]
That looks like a TypeScript error and not any actual runtime error. Upgrade to the latest Deno version and see if it still shows that error, and if it does try
```bash
deno run -Ar --no-check --unstable https://deno.land/x/webview/examples/local.ts
```
and see if that works

**Comment by martin-braun** [comment]
@b-fuze well done, it works. You are probably right with the Deno version, deno 1.19.3 and 1.20.3 works like charm.
