### ISSUE TITLE
Basic example does not work on Windows

### ISSUE THREAD

**Issue by jprochazk** [webview/webview_deno#126]
I'm running Windows 10, with `deno --version`:
```
deno 1.23.0 (release, x86_64-pc-windows-msvc)
v8 10.4.132.5
typescript 4.7.2
```
I have webview2 103.0.1264.37 installed.

Running `deno run -Ar --unstable https://deno.land/x/webview/examples/local.ts` in an empty directory yields:

```
Download https://deno.land/x/webview/examples/local.ts
Warning Implicitly using latest version (0.7.3) for https://deno.land/x/webview/examples/local.ts
Download https://deno.land/x/webview@0.7.3/examples/local.ts
Download https://deno.land/x/webview@0.7.3/mod.ts
Download https://deno.land/x/webview@0.7.3/src/ffi.ts
Download https://deno.land/x/webview@0.7.3/src/webview.ts
Download https://deno.land/x/webview@0.7.3/deps.ts
Download https://deno.land/std@0.145.0/path/mod.ts
Download https://deno.land/x/plug@0.5.2/plug.ts
Download https://deno.land/x/plug@0.5.2/deps.ts
Download https://deno.land/std@0.145.0/_util/os.ts
Download https://deno.land/std@0.145.0/path/_interface.ts
Download https://deno.land/std@0.145.0/path/common.ts
Download https://deno.land/std@0.145.0/path/glob.ts
Download https://deno.land/std@0.145.0/path/posix.ts
Download https://deno.land/std@0.145.0/path/separator.ts
Download https://deno.land/std@0.145.0/path/win32.ts
Download https://deno.land/std@0.122.0/fmt/colors.ts
Download https://deno.land/std@0.122.0/path/mod.ts
Download https://deno.land/x/cache@0.2.13/mod.ts
Download https://deno.land/std@0.122.0/_util/os.ts
Download https://deno.land/std@0.122.0/path/_interface.ts
Download https://deno.land/std@0.122.0/path/common.ts
Download https://deno.land/std@0.122.0/path/glob.ts
Download https://deno.land/std@0.122.0/path/posix.ts
Download https://deno.land/std@0.122.0/path/separator.ts
Download https://deno.land/std@0.122.0/path/win32.ts
Download https://deno.land/std@0.145.0/_util/assert.ts
Download https://deno.land/std@0.145.0/path/_constants.ts
Download https://deno.land/std@0.145.0/path/_util.ts
Download https://deno.land/x/cache@0.2.13/cache.ts
Download https://deno.land/std@0.122.0/path/_constants.ts
Download https://deno.land/std@0.122.0/path/_util.ts
Download https://deno.land/x/cache@0.2.13/deps.ts
Download https://deno.land/x/cache@0.2.13/directories.ts
Download https://deno.land/x/cache@0.2.13/file.ts
Download https://deno.land/x/cache@0.2.13/helpers.ts
Download https://deno.land/std@0.122.0/_util/assert.ts
Download https://deno.land/std@0.97.0/fs/ensure_dir.ts
Download https://deno.land/std@0.97.0/fs/exists.ts
Download https://deno.land/std@0.97.0/hash/mod.ts
Download https://deno.land/std@0.97.0/path/mod.ts
Download https://deno.land/x/cache@0.2.13/file_fetcher.ts
Download https://deno.land/std@0.97.0/fs/_util.ts
Download https://deno.land/std@0.97.0/hash/_wasm/hash.ts
Download https://deno.land/std@0.97.0/hash/hasher.ts
Download https://deno.land/std@0.97.0/_util/os.ts
Download https://deno.land/std@0.97.0/path/_interface.ts
Download https://deno.land/std@0.97.0/path/common.ts
Download https://deno.land/std@0.97.0/path/glob.ts
Download https://deno.land/std@0.97.0/path/posix.ts
Download https://deno.land/std@0.97.0/path/separator.ts
Download https://deno.land/std@0.97.0/path/win32.ts
Download https://deno.land/std@0.97.0/encoding/base64.ts
Download https://deno.land/std@0.97.0/encoding/hex.ts
Download https://deno.land/std@0.97.0/hash/_wasm/wasm.js
Download https://deno.land/std@0.97.0/_util/assert.ts
Download https://deno.land/std@0.97.0/path/_constants.ts
Download https://deno.land/std@0.97.0/path/_util.ts
error: Uncaught (in promise) TypeError: Error parsing args at position 0: data did not match any variant of untagged enum ForeignSymbol
  return Deno.dlopen(file, symbols);
              ^
    at Object.opSync (deno:core/01_core.js:170:38)
    at new DynamicLibrary (deno:ext/ffi/00_ffi.js:256:24)
    at Object.dlopen (deno:ext/ffi/00_ffi.js:350:12)
    at prepare (https://deno.land/x/plug@0.5.2/plug.ts:117:15)
    at async https://deno.land/x/webview@0.7.3/src/ffi.ts:90:13
```

**Comment by spamshaker** [comment]
same issue on Mac M1

**Comment by hironichu** [comment]
You need to update Deno to the latest release 1.23.1 !

**Comment by ybabts** [comment]
> You need to update Deno to the latest release 1.23.1 !

I'm getting the same error using version 1.23.1 attempting the same example as [jprochazk](https://github.com/jprochazk).

```
deno 1.23.1 (release, x86_64-pc-windows-msvc)
v8 10.4.132.8
typescript 4.7.2
```
