### ISSUE TITLE
Can't run demo from readme - TypeError: Error parsing args at position 0: data did not match any variant of untagged enum ForeignSymbol   return Deno.dlopen(file, symbols);

### ISSUE THREAD

**Issue by blipk** [webview/webview_deno#140]
Tried to run the demo from the readme either locally or from remote but run straight into this error:

```
error: Uncaught (in promise) TypeError: Error parsing args at position 0: data did not match any variant of untagged enum ForeignSymbol
  return Deno.dlopen(file, symbols);
              ^
    at new DynamicLibrary (deno:ext/ffi/00_ffi.js:286:39)
    at Object.dlopen (deno:ext/ffi/00_ffi.js:390:12)
    at prepare (https://deno.land/x/plug@0.5.2/plug.ts:117:15)
    at async https://deno.land/x/webview@0.7.4/src/ffi.ts:102:20
```

**Comment by eliotlim** [comment]
Hey @blipk,

I was trying to run webview-deno on my computer (arm64-apple-darwin21.6.0).

Just wanted you to know that I encountered the exact same error message:
```
error: Uncaught (in promise) TypeError: Error parsing args at position 0: data did not match any variant of untagged enum ForeignSymbol
  return Deno.dlopen(file, symbols);
              ^
    at new DynamicLibrary (deno:ext/ffi/00_ffi.js:286:39)
    at Object.dlopen (deno:ext/ffi/00_ffi.js:390:12)
    at prepare (https://deno.land/x/plug@0.5.2/plug.ts:117:15)
    at async https://deno.land/x/webview@0.7.4/src/ffi.ts:102:20
```

I found that upgrading deno to `1.25.4 from `1.24.3` solved this problem.

```
webview-deno % brew install deno
Running `brew update --auto-update`... output redacted

You have 80 outdated formulae and 1 outdated cask installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

deno 1.24.3 is already installed but outdated (so it will be upgraded).
==> Upgrading deno
  1.24.3 -> 1.25.4 
```

**Comment by blipk** [comment]
Thanks @eliotlim appreciate the response
Looks like distro upgraded to `1.25.1` recently and it's working there.
