### ISSUE TITLE
 webview + fresh for an Electron like application.

### ISSUE THREAD

**Issue by UrielCh** [webview/webview_deno#146]
Hi,

I want to display a fresh application in a web view, but strangely it do not work.

I made a few patchs to the default deno fresh main.ts file:

```typescript
/// <reference no-default-lib="true" />
/// <reference lib="dom" />
/// <reference lib="dom.iterable" />
/// <reference lib="dom.asynciterable" />
/// <reference lib="deno.ns" />

import { Webview } from "https://deno.land/x/webview@0.7.5/mod.ts";
import { getFreePort } from 'https://deno.land/x/free_port@v1.2.0/mod.ts'
import { start } from "$fresh/server.ts";
import manifest from "./fresh.gen.ts";
import twindPlugin from "$fresh/plugins/twind.ts";
import twindConfig from "./twind.config.ts";

// Choose a random free port
const port = await getFreePort(8000);

// I removed the await here, the start Promise never get resolved.
// I do not known how to detect if the service is ready, but that not my main issue
start(manifest, { plugins: [twindPlugin(twindConfig)], port });

// Wait 2 sec
console.log(`Starting on URL: http://127.0.0.1:${port}/ wait 2 Sec`)
await new Promise(r => setTimeout(r, 2000));
console.log(`Openning URL http://127.0.0.1:${port}/ in webview`)

const webview = new Webview();
webview.navigate(`http://127.0.0.1:${port}/`);
webview.run();
```

with this main, the webview gets displayed, but without the webserver, then when I close the webview, the server starts.

**Comment by UrielCh** [comment]
```typescript
webview.run();
```
is sync 😞

**Comment by andykais** [comment]
@UrielCh can you share how you got fresh working in a worker? The `window` variable is undefined in deno workers, which causes fresh to fail. E.g.
```
error: Uncaught (in worker "") (in promise) TypeError: Cannot read properties of undefined (reading '__PREACT_DEVTOOLS__')
    at https://esm.sh/stable/preact@10.15.1/denonext/devtools.js:2:166
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:159:19)
    at eventLoopTick (ext:core/01_core.js:183:11)```
