### ISSUE TITLE
Argument of type 'string | URL' is not assignable to parameter of type 'string'

### ISSUE THREAD

**Issue by Diomas** [webview/webview_deno#46]
I've installed recent deno and have copied `multiple.ts` example from `/examples` in the current webview_deno master

When I run `deno run --unstable multiple.ts` I'm getting these errors:
```
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@v0.51.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@v0.51.0/path/posix.ts:433:18

Found 2 errors.
```

Here's what I've found: https://dev.to/srnv/deno-1-2-0-url-argument-type-solutions-37m0

**Comment by Diomas** [comment]
ok, I've forgot `-r` for `deno run` so the webview was outdated

btw, how do I check which version of webview is installed?
