### ISSUE TITLE
crash: invalid promise id: expected type `rusty_v8::data::Integer`, got `rusty_v8::data::Value`

### ISSUE THREAD

**Issue by jcc10** [webview/webview_deno#76]
I am getting a crash with the following error:

```
...
Check https://deno.land/x/webview/examples/local.ts
Download https://github.com/webview/webview_deno/releases/download/0.5.6/libwebview_deno.so
error: Uncaught (in promise) TypeError: invalid promise id: expected type `rusty_v8::data::Integer`, got `rusty_v8::data::Value`
  const response = Plug.core.dispatch(opId, encode(data))!;
                             ^
    at sync (https://deno.land/x/webview@0.5.6/plugin.ts:53:30)
    at new Webview (https://deno.land/x/webview@0.5.6/webview.ts:58:22)
    at https://deno.land/x/webview@0.5.6/examples/local.ts:11:17
```

**Comment by eliassjogreen** [comment]
Plugins are currently broken in preparation for deno 1.10 where a total overhaul of them will be made.

**Comment by eliassjogreen** [comment]
[deno#10427](https://github.com/denoland/deno/pull/10427)
