### ISSUE TITLE
Could not open library "libwebkit2gtk-4.0.so.37"

### ISSUE THREAD

**Issue by Fowindev** [webview/webview_deno#77]
`error: Uncaught Error: Could not open library: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory
    at processResponse (core.js:226:13)
    at Object.jsonOpSync (core.js:250:12)
    at Object.openPlugin (deno:cli/rt/40_plugins.js:7:17)
    at Module.prepare (https://deno.land/x/plug@0.2.6/plug.ts:82:15)
    at async load (https://deno.land/x/webview@0.5.5/plugin.ts:75:9)
    at async https://deno.land/x/webview@0.5.5/mod.ts:5:1`

From : `deno run -Ar --unstable https://deno.land/x/webview/examples/local.ts`
OS: Fedora

**Comment by eliassjogreen** [comment]
You most probably don't have `libwebkit2gtk` installed, install it with `sudo apt-get install libwebkit2gtk-4.0-dev` or whatever it is on fedora

**Comment by offblacc** [comment]
On fedora it's:
`sudo dnf install webkit2gtk3`
