### ISSUE TITLE
Could not obtain symbol from the library: The specified procedure could not be found.

### ISSUE THREAD

**Issue by CoderNinja123** [webview/webview_deno#80]
Hi, while running the following script

```js
import { Webview } from "https://deno.land/x/webview@0.5.6/mod.ts";

const webview = new Webview(
  { url: "https://deno.land" },
);
await webview.run();
```
I am getting the error

```
error: Uncaught (in promise) Error: Could not obtain symbol from the library: The specified procedure could not be found. (os error 127)
```

Additional Output:
```
Download https://github.com/webview/webview_deno/releases/download/0.5.6/webview_deno.dll
error: Uncaught (in promise) Error: Could not obtain symbol from the library: The specified procedure could not be found. (os error 127)
  return Deno.openPlugin(file.path);
              ^
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at Object.opSync (deno:core/core.js:120:12)
    at Object.openPlugin (deno:runtime/js/40_plugins.js:8:22)
    at Module.prepare (https://deno.land/x/plug@0.2.9/plug.ts:87:15)
    at async load (https://deno.land/x/webview@0.5.6/plugin.ts:75:9)
    at async https://deno.land/x/webview@0.5.6/mod.ts:5:1
```

I ran the following command:

```
> deno run -A --unstable webview.js
```

Deno version
```
deno 1.10.1 (release, x86_64-pc-windows-msvc)
v8 9.1.269.27
typescript 4.2.2
```

**Comment by eliassjogreen** [comment]
The current latest working release of webview_deno is meant for deno 1.8. A 1.10 version is coming soon
