### ISSUE TITLE
Can't run example (webview 0.5.6)

### ISSUE THREAD

**Issue by danaugrs** [webview/webview_deno#81]
deno 1.10.2 (release, x86_64-unknown-linux-gnu)
v8 9.1.269.27
typescript 4.2.2
webview 0.5.6

`deno run -Ar --unstable https://deno.land/x/webview@0.5.6/examples/local.ts`

fails with

```
Download https://github.com/webview/webview_deno/releases/download/0.5.6/libwebview_deno.so
error: Uncaught (in promise) Error: Could not obtain symbol from the library: /home/danaugrs/.cache/deno/plug/https/github.com/b1d03bdcfe69960f0dfe0c71a4efcec9d3c3a807748d69b610802e27ddda8bd4.so: undefined symbol: init
  return Deno.openPlugin(file.path);
              ^
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at Object.opSync (deno:core/core.js:120:12)
    at Object.openPlugin (deno:runtime/js/40_plugins.js:8:22)
    at Module.prepare (https://deno.land/x/plug@0.2.9/plug.ts:87:15)
    at async load (https://deno.land/x/webview@0.5.6/plugin.ts:75:9)
    at async https://deno.land/x/webview@0.5.6/mod.ts:5:1
```
I'm on Ubuntu 21.04.

**Comment by eliassjogreen** [comment]
#79
