### ISSUE TITLE
Uncaught Error: Could not open library: The specified module could not be found. (os error 126)

### ISSUE THREAD

**Issue by amirnd** [webview/webview_deno#83]
Hi. I'm not sure if there was any issue related to this - at least i didn't find anything - so I am asking directly here.
I tried using deno_webview several times but i kept getting an error. After updating Deno to:
```
deno 1.10.2 (release, x86_64-pc-windows-msvc)
v8 9.1.269.27
typescript 4.2.2
```
The output is:
```
Check file:///D:/Code/webview_deno/main.ts
Plugin exists:  D:\Code\webview_deno\webview_deno.dll
error: Uncaught Error: Could not open library: The specified module could not be found. (os error 126)
Deno.openPlugin(PLUGIN);
     ^
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at Object.opSync (deno:core/core.js:120:12)
    at Object.openPlugin (deno:runtime/js/40_plugins.js:8:22)
    at file:///D:/Code/webview_deno/main.ts:12:6

```

And this is the source:
```
let PLUGIN = './webview_deno.dll';
if (Deno.statSync(PLUGIN).isFile) {
  PLUGIN = Deno.realPathSync(PLUGIN);
  console.log('Plugin exists: ', PLUGIN);
} else {
  console.log("Plugin not found");
  Deno.exit();
}
Deno.openPlugin(PLUGIN);
```

Directory list:
```
.vscode
main.ts
webview_deno.dll
```

**Comment by eliassjogreen** [comment]
This is because the up and coming `webiew_rust` based release will require the `Webview2Loader.dll` in cwd. It is automatically downloaded and copied to the directory [here](https://github.com/webview/webview_deno/blob/webview_rust/plugin.ts#L11-L21).
