### ISSUE TITLE
Incompatible with `Deno@v1.13.1` (latest)

### ISSUE THREAD

**Issue by seirakei** [webview/webview_deno#93]
Running the example:
```sh
$ deno run -Ar --unstable https://deno.land/x/webview/examples/local.ts
```

Error:
```
error: TS2345 [ERROR]: Argument of type '{ url: string; }' is not assignable to parameter of type 'boolean | undefined'.
  Type '{ url: string; }' is not assignable to type 'true'.
  { url: `data:text/html,${encodeURIComponent(html)}` },
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/webview@0.6.0-pre.0/examples/local.ts:12:3
 ```

Well, this is maybe just a typescript related problem.

Running the example (without type checking):
```sh
$ deno run -Ar --unstable --no-check https://deno.land/x/webview/examples/local.ts
```

Error:
```
error: Uncaught (in promise) TypeError: Deno.openPlugin is not a function
  return Deno.openPlugin(file.path);
              ^
    at Module.prepare (https://deno.land/x/plug@0.3.0/plug.ts:85:15)
    at async https://deno.land/x/webview@0.6.0-pre.0/plugin.ts:8:73
 ```
 
 This library have potential but it looks like it's abandoned

**Comment by seirakei** [comment]
Full output of `deno --version` if it helps:
```
$ deno --version
deno 1.13.1 (release, x86_64-pc-windows-msvc)
v8 9.3.345.11
typescript 4.3.5
```

**Comment by seirakei** [comment]
As stated [here](https://github.com/webview/webview_deno/issues/89#issuecomment-897546075), I need to wait for the pr to be merged. I'm closing this issue.
